---
- name: check docker storage driver
  ansible.builtin.assert:
    that:
      - docker_storage_driver == "overlay2" or docker_storage_driver == "vfs"
    quiet: true

- ansible.builtin.include_tasks: docker.yml
  when: ansible_os_family == "RedHat"
  tags:
    - ferm-conf
    - kresd-conf
