---

- name: /var/lib/docker directory
  file:
    path: /var/lib/docker
    state: directory
    owner: root
    group: root
    mode: '0711'

- name: docker storage configuration
  template:
    src: storage-setup-docker.conf.j2
    dest: /etc/filesystems.d/20-docker.conf
    mode: 0644
